export enum AuthActionTypes {
  SOCIAL_LOGIN = "@@AUTH/SOCIAL_LOGIN",
  SOCIAL_LOGIN_SUCCESS = "@@AUTH/SOCIAL_LOGIN_SUCCESS",
  SOCIAL_LOGIN_FAILURE = "@@AUTH/SOCIAL_LOGIN_FAILURE",

  LOG_OUT = "@@AUTH/LOG_OUT",

  UPDATE_USER_DATA = "@@AUTH/UPDATE_USER_DATA",
  UPDATE_USER_DATA_SUCCESS = "@@AUTH/UPDATE_USER_DATA_SUCCESS",
  UPDATE_USER_DATA_FAILURE = "@@AUTH/UPDATE_USER_DATA_FAILURE",

  SET_IS_NEW_USER = "@@AUTH/SET_IS_NEW_USER",
}
