export enum TrusteeActionTypes {
  GET_PENDING_APPROVAL_PROPOSALS = "@TRUSTEE/GET_PENDING_APPROVAL_PROPOSALS",
  GET_PENDING_APPROVAL_PROPOSALS_SUCCESS = "@TRUSTEE/GET_PENDING_APPROVAL_PROPOSALS_SUCCESS",
  GET_PENDING_APPROVAL_PROPOSALS_FAILURE = "@TRUSTEE/GET_PENDING_APPROVAL_PROPOSALS_FAILURE",

  GET_APPROVED_PROPOSALS = "@TRUSTEE/GET_APPROVED_PROPOSALS",
  GET_APPROVED_PROPOSALS_SUCCESS = "@TRUSTEE/GET_APPROVED_PROPOSALS_SUCCESS",
  GET_APPROVED_PROPOSALS_FAILURE = "@TRUSTEE/GET_APPROVED_PROPOSALS_FAILURE",

  GET_DECLINED_PROPOSALS = "@TRUSTEE/GET_DECLINED_PROPOSALS",
  GET_DECLINED_PROPOSALS_SUCCESS = "@TRUSTEE/GET_DECLINED_PROPOSALS_SUCCESS",
  GET_DECLINED_PROPOSALS_FAILURE = "@TRUSTEE/GET_DECLINED_PROPOSALS_FAILURE",
}
