version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    hostname: redis
    restart: unless-stopped
    networks: [internal]
  postgres:
    image: "postgres:13"
    container_name: postrges-db
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
    volumes:
      - ./:/var/lib/postgres:rw
    networks: [internal]
  worker:
    image: common-backend-alpine
    container_name: common-worker
    ports:
     - "4001:4001"
    depends_on:
      - postgres
      - redis
      - init-db
    command: worker
    env_file: [".env"]
    networks: [internal, host]
  graphql:
    image: common-backend-alpine
    container_name: common-graphql
    ports:
     - "4000:4000"
    depends_on:
      - postgres
      - redis
      - init-db
    command: graphql
    env_file: [".env"]
    networks: [internal, host]
  init-db:
    image: common-backend-alpine
    restart: "no"
    working_dir: /app/packages/core
    env_file: [".env"]
    command: init-db
    networks: [internal]
networks:
  internal:
  host:
