version: '2'
services:
  redis:
    image: "redis:alpine"
    container_name: redis  
    restart: unless-stopped
  postgres:
    image: "postgres:13"
    container_name: postrges-db
    restart: unless-stopped
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres
  backend:
    build: .
    container_name: common-backend
    ports:
     - "81:8080"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    command: ["npm", "start"]