export enum ChatActionTypes {
  SET_DISCUSSION_MESSAGE_REPLY = "@CHAT/SET_DISCUSSION_MESSAGE_REPLY",
  CLEAR_DISCUSSION_MESSAGE_REPLY = "@CHAT/CLEAR_DISCUSSION_MESSAGE_REPLY",
  SET_FILES_PREVIEW = "@CHAT/SET_FILES_PREVIEW",
  CLEAR_FILES_PREVIEW = "@CHAT/CLEAR_FILES_PREVIEW",
}
