"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.proposalsService = exports.joinProposalService = exports.paymentService = exports.commonService = exports.eventsService = exports.cardsService = exports.voteService = exports.userService = void 0;
var users_1 = require("./users");
Object.defineProperty(exports, "userService", { enumerable: true, get: function () { return users_1.userService; } });
var votes_1 = require("./votes");
Object.defineProperty(exports, "voteService", { enumerable: true, get: function () { return votes_1.voteService; } });
var cards_1 = require("./cards");
Object.defineProperty(exports, "cardsService", { enumerable: true, get: function () { return cards_1.cardsService; } });
var events_1 = require("./events");
Object.defineProperty(exports, "eventsService", { enumerable: true, get: function () { return events_1.eventsService; } });
var commons_1 = require("./commons");
Object.defineProperty(exports, "commonService", { enumerable: true, get: function () { return commons_1.commonService; } });
var payments_1 = require("./payments");
Object.defineProperty(exports, "paymentService", { enumerable: true, get: function () { return payments_1.paymentService; } });
var proposals_1 = require("./proposals");
Object.defineProperty(exports, "joinProposalService", { enumerable: true, get: function () { return proposals_1.joinProposalService; } });
Object.defineProperty(exports, "proposalsService", { enumerable: true, get: function () { return proposals_1.proposalsService; } });
