export const ApiEndpoint = {
  GovernanceCreate: "/api/governance/create",
  GovernanceUpdateRules: "/api/governance/updateRules",
  AddFounderToMembers: "/api/commons/add-founder-to-members",
  CreateCommon: "/api/commons/create",
  UpdateCommon: "/api/commons/update",
  CreateSubCommon: "/api/commons/subcommon/create",
  MarkFeedObjectSeenForUser: "/api/commons/mark-feed-object-seen-for-user",
  MarkFeedObjectUnseenForUser: "/api/commons/mark-feed-object-unseen-for-user",
  AcceptRules: "/api/commons/accept-rules",
  GetCommonFeedItems: "/api/commons/:commonId/feed-items",
  GetCommonPinnedFeedItems: "/api/commons/:commonId/pinned-feed-items",
  CreateAction: "/api/proposals/action",
  CreateProposal: "/api/proposals/create",
  VoteProposal: "/api/proposals/vote",
  UpdateVote: "/api/proposals/vote",
  MakeImmediateContribution: "/api/commons/immediate-contribution",
  AddBankAccount: "/api/payments/bank-account-details/add",
  UpdateBankAccount: "/api/payments/bank-account-details/update",
  DeleteBankAccount: "/api/payments/bank-account-details/delete",
  GetBankAccount: "/api/payments/bank-account-details/get",
  UploadInvoices: "/api/payments/payout-docs/add",
  ApproveOrDeclineProposal: "/api/payments/payout-docs/trustee-decision",
  GetReports: "/api/reports",
  CreateReport: "/api/moderation/report",
  HideContent: "/api/moderation/hide",
  ShowContent: "/api/moderation/show",
  LeaveCommon: "/api/commons/leave",
  CreateSubscription: "/api/commons/immediate-contribution",
  UpdateSubscription: "/api/subscriptions/update",
  CancelSubscription: "/api/subscriptions/cancel",
  CreateUser: "/api/users/create",
  DeleteUser: "/api/users/delete",
  FollowFeedItem: "/api/users/follow-feed-item",
  GetInbox: "/api/users/inbox",
  SendEmail: "/api/notifications/send-email",
  SeenNotification: "/api/notifications/seen",
  CreateDiscussion: "/api/discussions/create",
  EditDiscussion: "/api/discussions/edit",
  DeleteDiscussion: (id: string) => `/api/discussions/delete/${id}`,
  CreateDiscussionMessage: "/api/discussions/message",
  DeleteDiscussionMessage: "/api/discussions/delete",
  GetProposalEligibleVoters:
    "/api/proposals/get-all-eligible-proposal-voters/:proposalId",
  GetDMUsers: "/api/chat/users",
  CreateChatChannel: "/api/chat/channel",
  GetChatChannelMessages: (channelId: string) =>
    `/api/chat/channel/${channelId}/messages`,
  SendChatMessage: (channelId: string) => `/api/chat/${channelId}/message`,
  UpdateChatMessage: (chatMessageId: string) =>
    `/api/chat/message/${chatMessageId}`,
  DeleteChatMessage: (chatMessageId: string) =>
    `/api/chat/message/${chatMessageId}`,
  MarkChatChannelAsSeen: (channelId: string) =>
    `/api/chat/channel/${channelId}/seen`,
  MarkChatMessageAsSeen: (chatMessageId: string) =>
    `/api/chat/message/${chatMessageId}/seen`,
};
