export enum ROUTE_PATHS {
  HOME = "/",
  MY_ACCOUNT = "/my-account",
  MY_ACCOUNT_PROFILE = "/my-account/profile",
  MY_ACCOUNT_ACTIVITIES = "/my-account/activities",
  MY_ACCOUNT_ACTIVITIES_PROPOSALS = "/my-account/activities/proposals",
  MY_ACCOUNT_ACTIVITIES_MEMBERSHIP_REQUESTS = "/my-account/activities/membership-requests",
  MY_ACCOUNT_BILLING = "/my-account/billing",
  COMMON_LIST = "/commons",
  COMMON_DETAIL = "/commons/:id",
  CONTACT = "/contact",
  MY_COMMONS = "/my-commons",
  SUBMIT_INVOICES = "/invoices/submission/:proposalId",
  TRUSTEE = "/trustee",
  TRUSTEE_AUTH = "/trustee/auth",
  TRUSTEE_INVOICES = "/trustee/invoices",
  TRUSTEE_INVOICE = "/trustee/invoices/:proposalId",
}
