export enum Theme {
  Light = "light",
  Dark = "dark",
}

export enum ThemeColors {
  primaryBackground,
  secondaryBackground,
  hoverFill,
  secondaryHoverFill,
  primaryText,
  secondaryText,
  gentleStroke,
  warning,
  primaryFill,
  secondaryFill,
  tertiaryFill,
  quaternaryFill,
  quinaryFill,
  dropShadow,
}

export const ThemeColorsValues = {
  [Theme.Light]: {
    [ThemeColors.primaryBackground]: "#ffffff",
    [ThemeColors.secondaryBackground]: "#f8f8f5",
    [ThemeColors.hoverFill]: "#FBF1F8",
    [ThemeColors.secondaryHoverFill]: "#FBF1F8",
    [ThemeColors.primaryText]: "#001a36",
    [ThemeColors.secondaryText]: "#a75a93",
    [ThemeColors.gentleStroke]: "#f4f5f5",
    [ThemeColors.warning]: "#ff603e",
    [ThemeColors.primaryFill]: "#D84C7F",
    [ThemeColors.secondaryFill]: "#B5406A",
    [ThemeColors.tertiaryFill]: "#ffffff",
    [ThemeColors.quaternaryFill]: "#7A2845",
    [ThemeColors.quinaryFill]: "#EDCEDF",
    [ThemeColors.dropShadow]: "rgba(0, 0, 0, 0.15259)",
  },
  [Theme.Dark]: {
    [ThemeColors.primaryBackground]: "#101010",
    [ThemeColors.secondaryBackground]: "#1F2124",
    [ThemeColors.hoverFill]: "#432B33",
    [ThemeColors.secondaryHoverFill]: "#432B33",
    [ThemeColors.primaryText]: "#ffffff",
    [ThemeColors.secondaryText]: "#a75a93",
    [ThemeColors.gentleStroke]: "#2e3452",
    [ThemeColors.warning]: "#ff603e",
    [ThemeColors.primaryFill]: "#D84C7F",
    [ThemeColors.secondaryFill]: "#CF7D9B",
    [ThemeColors.tertiaryFill]: "#131b23",
    [ThemeColors.quaternaryFill]: "#EF9DBA",
    [ThemeColors.quinaryFill]: "#432B33",
    [ThemeColors.dropShadow]: "rgba(0, 0, 0, 0.15259)",
  },
};
