export enum CommonsActionTypes {
  GET_COMMONS_LIST = "@COMMONS/GET_COMMONS_LIST",
  GET_COMMONS_LIST_SUCCESS = "@COMMONS/GET_COMMONS_LIST_SUCCESS",
  GET_COMMONS_LIST_FAILURE = "@COMMONS/GET_COMMONS_LIST_FAILURE",

  GET_COMMON_DETAIL = "@COMMONS/GET_COMMON_DETAIL",
  GET_COMMON_DETAIL_SUCCESS = "@COMMONS/GET_COMMON_DETAIL_SUCCESS",
  GET_COMMON_DETAIL_FAILURE = "@COMMONS/GET_COMMON_DETAIL_FAILURE",

  UPDATE_PAGE = "@COMMONS/UPDATE_PAGE",

  SET_DISCUSSION = "@COMMONS/SET_DISCUSSIONS",

  SET_PROPOSALS = "@COMMONS/SET_PROPOSALS",
}
