export enum ProjectsActionType {
  GET_PROJECTS = "@PROJECTS/GET_PROJECTS",
  GET_PROJECTS_SUCCESS = "@PROJECTS/GET_PROJECTS_SUCCESS",
  GET_PROJECTS_FAILURE = "@PROJECTS/GET_PROJECTS_FAILURE",

  UPDATE_PROJECT = "@PROJECTS/UPDATE_PROJECT",

  CLEAR_PROJECTS = "@PROJECTS/CLEAR_PROJECTS",
}
