export enum CommonsActionTypes {
  GET_COMMONS_LIST = "@COMMONS/GET_COMMONS_LIST",
  GET_COMMONS_LIST_SUCCESS = "@COMMONS/GET_COMMONS_LIST_SUCCESS",
  GET_COMMONS_LIST_FAILURE = "@COMMONS/GET_COMMONS_LIST_FAILURE",

  GET_COMMON_DETAIL = "@COMMONS/GET_COMMON_DETAIL",
  GET_COMMON_DETAIL_SUCCESS = "@COMMONS/GET_COMMON_DETAIL_SUCCESS",
  GET_COMMON_DETAIL_FAILURE = "@COMMONS/GET_COMMON_DETAIL_FAILURE",

  UPDATE_PAGE = "@COMMONS/UPDATE_PAGE",

  SET_DISCUSSION = "@COMMONS/SET_DISCUSSIONS",

  SET_PROPOSALS = "@COMMONS/SET_PROPOSALS",

  LOAD_COMMON_DISCUSSIONS = "@COMMONS/LOAD_COMMON_DISCUSSIONS",
  LOAD_COMMON_DISCUSSIONS_SUCCESS = "@COMMONS/LOAD_COMMON_DISCUSSIONS_SUCCESS",
  LOAD_COMMON_DISCUSSIONS_FAILURE = "@COMMONS/LOAD_COMMON_DISCUSSIONS_FAILURE",

  LOAD_DISCUSSION_DETAIL = "@COMMONS/LOAD_DISCUSSION_DETAIL",
  LOAD_DISCUSSION_DETAIL_SUCCESS = "@COMMONS/LOAD_DISCUSSION_DETAIL_SUCCESS",
  LOAD_DISCUSSION_DETAIL_FAILURE = "@COMMONS/LOAD_DISCUSSION_DETAIL_FAILURE",

  CLEAR_CURRENT_DISCUSSION = "@COMMONS/CLEAR_CURRENT_DISCUSSION",

  CLEAR_CURRENT_PROPOSAL = "@COMMONS/CLEAR_CURRENT_PROPOSAL",

  CLOSE_CURRENT_COMMON = "@COMMONS/CLOSE_CURRENT_COMMON",

  LOAD_PROPOSAL_LIST = "@COMMONS/LOAD_PROPOSAL_LIST",
  LOAD_PROPOSAL_LIST_SUCCESS = "@COMMONS/LOAD_PROPOSAL_LIST_SUCCESS",
  LOAD_PROPOSAL_LIST_FAILURE = "@COMMONS/LOAD_PROPOSAL_LIST_FAILURE",

  LOAD_PROPOSAL_DETAIL = "@COMMONS/LOAD_PROPOSAL_DETAIL",
  LOAD_PROPOSAL_DETAIL_SUCCESS = "@COMMONS/LOAD_PROPOSAL_DETAIL_SUCCESS",
  LOAD_PROPOSAL_DETAIL_FAILURE = "@COMMONS/LOAD_PROPOSAL_DETAIL_FAILURE",

  LOAD_USER_PROPOSAL_LIST = "@COMMONS/LOAD_USER_PROPOSAL_LIST",
  LOAD_USER_PROPOSAL_LIST_SUCCESS = "@COMMONS/LOAD_USER_PROPOSAL_LIST_SUCCESS",
  LOAD_USER_PROPOSAL_LIST_FAILURE = "@COMMONS/LOAD_USER_PROPOSAL_LIST_FAILURE",

  CREATE_DISCUSSION = "@@COMMONS/CREATE_DISCUSSION",
  CREATE_DISCUSSION_SUCCESS = "@@COMMONS/CREATE_DISCUSSION_SUCCESS",
  CREATE_DISCUSSION_FAILURE = "@@COMMONS/CREATE_DISCUSSION_FAILURE",

  ADD_MESSAGE_TO_DISCUSSION = "@@COMMONS/ADD_MESSAGE_TO_DISCUSSION",
  ADD_MESSAGE_TO_DISCUSSION_SUCCESS = "@@COMMONS/ADD_MESSAGE_TO_DISCUSSION_SUCCESS",
  ADD_MESSAGE_TO_DISCUSSION_FAILURE = "@@COMMONS/ADD_MESSAGE_TO_DISCUSSION_FAILURE",

  CREATE_REQUEST_TO_JOIN = "@COMMONS/CREATE_REQUEST_TO_JOIN",
  CREATE_REQUEST_TO_JOIN_SUCCESS = "@COMMONS/CREATE_REQUEST_TO_JOIN_SUCCESS",
  CREATE_REQUEST_TO_JOIN_FAILURE = "@COMMONS/CREATE_REQUEST_TO_JOIN_FAILURE",

  CREATE_FUNDING_PROPOSAL = "@COMMONS/CREATE_FUNDING_PROPOSAL",
  CREATE_FUNDING_PROPOSAL_SUCCESS = "@COMMONS/CREATE_FUNDING_PROPOSAL_SUCCESS",
  CREATE_FUNDING_PROPOSAL_FAILURE = "@COMMONS/CREATE_FUNDING_PROPOSAL_FAILURE",

  CHECK_USER_PAYMENT_METHOD = "@COMMONS/CHECK_USER_PAYMENT_METHOD",
  CHECK_USER_PAYMENT_METHOD_SUCCESS = "@COMMONS/CHECK_USER_PAYMENT_METHOD_SUCCESS",
  CHECK_USER_PAYMENT_METHOD_FAILURE = "@COMMONS/CHECK_USER_PAYMENT_METHOD_FAILURE",
}
