export enum CommonsActionTypes {
  GET_COMMONS_LIST = "@COMMONS/GET_COMMONS_LIST",
  GET_COMMONS_LIST_SUCCESS = "@COMMONS/GET_COMMONS_LIST_SUCCESS",
  GET_COMMONS_LIST_FAILURE = "@COMMONS/GET_COMMONS_LIST_FAILURE",

  GET_COMMON_DETAIL = "@COMMONS/GET_COMMON_DETAIL",
  GET_COMMON_DETAIL_SUCCESS = "@COMMONS/GET_COMMON_DETAIL_SUCCESS",
  GET_COMMON_DETAIL_FAILURE = "@COMMONS/GET_COMMON_DETAIL_FAILURE",

  UPDATE_PAGE = "@COMMONS/UPDATE_PAGE",

  SET_DISCUSSION = "@COMMONS/SET_DISCUSSIONS",

  SET_PROPOSALS = "@COMMONS/SET_PROPOSALS",

  LOAD_COMMON_DISCUSSIONS = "@COMMONS/LOAD_COMMON_DISCUSSIONS",
  LOAD_COMMON_DISCUSSIONS_SUCCESS = "@COMMONS/LOAD_COMMON_DISCUSSIONS_SUCCESS",
  LOAD_COMMON_DISCUSSIONS_FAILURE = "@COMMONS/LOAD_COMMON_DISCUSSIONS_FAILURE",

  LOAD_DISCUSSION_DETAIL = "@COMMONS/LOAD_DISCUSSION_DETAIL",
  LOAD_DISCUSSION_DETAIL_SUCCESS = "@COMMONS/LOAD_DISCUSSION_DETAIL_SUCCESS",
  LOAD_DISCUSSION_DETAIL_FAILURE = "@COMMONS/LOAD_DISCUSSION_DETAIL_FAILURE",

  CLEAR_CURRENT_DISCUSSION = "@COMMONS/CLEAR_CURRENT_DISCUSSION",

  CLEAR_CURRENT_PROPOSAL = "@COMMONS/CLEAR_CURRENT_PROPOSAL",

  CLOSE_CURRENT_COMMON = "@COMMONS/CLOSE_CURRENT_COMMON",

  LOAD_PROPOSAL_LIST = "@COMMONS/LOAD_PROPOSAL_LIST",
  LOAD_PROPOSAL_LIST_SUCCESS = "@COMMONS/LOAD_PROPOSAL_LIST_SUCCESS",
  LOAD_PROPOSAL_LIST_FAILURE = "@COMMONS/LOAD_PROPOSAL_LIST_FAILURE",

  LOAD_PROPOSAL_DETAIL = "@COMMONS/LOAD_PROPOSAL_DETAIL",
  LOAD_PROPOSAL_DETAIL_SUCCESS = "@COMMONS/LOAD_PROPOSAL_DETAIL_SUCCESS",
  LOAD_PROPOSAL_DETAIL_FAILURE = "@COMMONS/LOAD_PROPOSAL_DETAIL_FAILURE",

  LOAD_USER_PROPOSAL_LIST = "@COMMONS/LOAD_USER_PROPOSAL_LIST",
  LOAD_USER_PROPOSAL_LIST_SUCCESS = "@COMMONS/LOAD_USER_PROPOSAL_LIST_SUCCESS",
  LOAD_USER_PROPOSAL_LIST_FAILURE = "@COMMONS/LOAD_USER_PROPOSAL_LIST_FAILURE",

  CREATE_DISCUSSION = "@@COMMONS/CREATE_DISCUSSION",
  CREATE_DISCUSSION_SUCCESS = "@@COMMONS/CREATE_DISCUSSION_SUCCESS",
  CREATE_DISCUSSION_FAILURE = "@@COMMONS/CREATE_DISCUSSION_FAILURE",

  ADD_MESSAGE_TO_DISCUSSION = "@@COMMONS/ADD_MESSAGE_TO_DISCUSSION",
  ADD_MESSAGE_TO_DISCUSSION_SUCCESS = "@@COMMONS/ADD_MESSAGE_TO_DISCUSSION_SUCCESS",
  ADD_MESSAGE_TO_DISCUSSION_FAILURE = "@@COMMONS/ADD_MESSAGE_TO_DISCUSSION_FAILURE",

  CREATE_REQUEST_TO_JOIN = "@COMMONS/CREATE_REQUEST_TO_JOIN",
  CREATE_REQUEST_TO_JOIN_SUCCESS = "@COMMONS/CREATE_REQUEST_TO_JOIN_SUCCESS",
  CREATE_REQUEST_TO_JOIN_FAILURE = "@COMMONS/CREATE_REQUEST_TO_JOIN_FAILURE",

  CREATE_FUNDING_PROPOSAL = "@COMMONS/CREATE_FUNDING_PROPOSAL",
  CREATE_FUNDING_PROPOSAL_SUCCESS = "@COMMONS/CREATE_FUNDING_PROPOSAL_SUCCESS",
  CREATE_FUNDING_PROPOSAL_FAILURE = "@COMMONS/CREATE_FUNDING_PROPOSAL_FAILURE",

  LOAD_USER_CARDS = "@COMMONS/LOAD_USER_CARDS",
  LOAD_USER_CARDS_SUCCESS = "@COMMONS/LOAD_USER_CARDS_SUCCESS",
  LOAD_USER_CARDS_FAILURE = "@COMMONS/LOAD_USER_CARDS_FAILURE",

  ADD_MESSAGE_TO_PROPOSAL = "@@COMMONS/ADD_MESSAGE_TO_PROPOSAL",
  ADD_MESSAGE_TO_PROPOSAL_SUCCESS = "@@COMMONS/ADD_MESSAGE_TO_PROPOSAL_SUCCESS",
  ADD_MESSAGE_TO_PROPOSAL_FAILURE = "@@COMMONS/ADD_MESSAGE_TO_PROPOSAL_FAILURE",

  DELETE_COMMON = "@COMMONS/DELETE_COMMON",
  DELETE_COMMON_SUCCESS = "@COMMONS/DELETE_COMMON_SUCCESS",
  DELETE_COMMON_FAILURE = "@COMMONS/DELETE_COMMON_FAILURE",

  CREATE_COMMON = "@COMMONS/CREATE_COMMON",
  CREATE_COMMON_SUCCESS = "@COMMONS/CREATE_COMMON_SUCCESS",
  CREATE_COMMON_FAILURE = "@COMMONS/CREATE_COMMON_FAILURE",

  CREATE_VOTE = "@COMMONS/CREATE_VOTE",
  CREATE_VOTE_SUCCESS = "@COMMONS/CREATE_VOTE_SUCCESS",
  CREATE_VOTE_FAILURE = "@COMMONS/CREATE_VOTE_FAILURE",

  MAKE_IMMEDIATE_CONTRIBUTION = "@COMMONS/MAKE_IMMEDIATE_CONTRIBUTION",
  MAKE_IMMEDIATE_CONTRIBUTION_SUCCESS = "@COMMONS/MAKE_IMMEDIATE_CONTRIBUTION_SUCCESS",
  MAKE_IMMEDIATE_CONTRIBUTION_FAILURE = "@COMMONS/MAKE_IMMEDIATE_CONTRIBUTION_FAILURE",

  ADD_BANK_DETAILS = "@COMMONS/ADD_BANK_DETAILS",
  ADD_BANK_DETAILS_SUCCESS = "@COMMONS/ADD_BANK_DETAILS_SUCCESS",
  ADD_BANK_DETAILS_FAILURE = "@COMMONS/ADD_BANK_DETAILS_FAILURE",

  GET_BANK_DETAILS = "@COMMONS/GET_BANK_DETAILS",
  GET_BANK_DETAILS_SUCCESS = "@COMMONS/GET_BANK_DETAILS_SUCCESS",
  GET_BANK_DETAILS_FAILURE = "@COMMONS/GET_BANK_DETAILS_FAILURE",
}
