export enum MultipleSpacesLayoutActionType {
  RESET = "@MULTIPLE_SPACES_LAYOUT/RESET",

  CONFIGURE_BREADCRUMBS_DATA = "@MULTIPLE_SPACES_LAYOUT/CONFIGURE_BREADCRUMBS_DATA",

  FETCH_BREADCRUMBS_ITEMS_BY_COMMON_ID = "@MULTIPLE_SPACES_LAYOUT/FETCH_BREADCRUMBS_ITEMS_BY_COMMON_ID",
  FETCH_BREADCRUMBS_ITEMS_BY_COMMON_ID_SUCCESS = "@MULTIPLE_SPACES_LAYOUT/FETCH_BREADCRUMBS_ITEMS_BY_COMMON_ID_SUCCESS",
  FETCH_BREADCRUMBS_ITEMS_BY_COMMON_ID_FAILURE = "@MULTIPLE_SPACES_LAYOUT/FETCH_BREADCRUMBS_ITEMS_BY_COMMON_ID_FAILURE",
  FETCH_BREADCRUMBS_ITEMS_BY_COMMON_ID_CANCEL = "@MULTIPLE_SPACES_LAYOUT/FETCH_BREADCRUMBS_ITEMS_BY_COMMON_ID_CANCEL",

  SET_BREADCRUMBS_DATA = "@MULTIPLE_SPACES_LAYOUT/SET_BREADCRUMBS_DATA",
}
