name: Lint

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.20.1'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Lint
        uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
