name: CloudFunctions Test CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0

      - name: Setting-up JAVA
        uses: actions/setup-java@v1.3.0
        with:
          java-version: "12.x"

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Start docker containers
        run: docker-compose up -d

      - name: Setup CI environment
        run: yarn use:ci --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Modify firebase.json
        run: npx json -I -f firebase.json -e "this.emulators.functions.port=5003"

      - name: Run tests
        run: |
          yarn emulator:headless &
          sleep 30 && yarn ci:test
