export enum SharedActionTypes {
  START_LOADING = "@@SHARED/START_LOADING",
  STOP_LOADING = "@@SHARED/STOP_LOADING",
  SHOW_NOTIFICATION = "@@SHARED/SHOW_NOTIFICATION",
  CHANGE_SCREEN_SIZE = "@@SHARED/CHANGE_SCREEN_SIZE",

  BUILD_SHARE_LINK = "@@SHARED/BUILD_SHARE_LINK",
  BUILD_SHARE_LINK_SUCCESS = "@@SHARED/BUILD_SHARE_LINK_SUCCESS",
  BUILD_SHARE_LINK_FAILURE = "@@SHARED/BUILD_SHARE_LINK_FAILURE",
}
