export enum GovernanceActions {
  SEND_INVITATION = "SEND_INVITATION",

  VIEW_COMMON = "VIEW_COMMON",

  VIEW_PROPOSAL = "VIEW_PROPOSAL",
  CREATE_PROPOSAL = "CREATE_PROPOSAL",

  CREATE_VOTE = "CREATE_VOTE",

  CREATE_DISCUSSION = "CREATE_DISCUSSION",
  VIEW_DISCUSSION = "VIEW_DISCUSSION",
  DELETE_DISCUSSION = "DELETE_DISCUSSION",

  CREATE_POST = "CREATE_POST",
  REPORT_POST = "REPORT_POST",
  DELETE_POST = "DELETE_POST",

  CONTRIBUTE = "CONTRIBUTE",

  RECIEVE_FUNDS = "RECIEVE_FUNDS",
}
