export const MOBILE_HEADER_HEIGHT = 52;
export const DESKTOP_HEADER_HEIGHT = 56 + 79;
export const MOBILE_TAB_NAVIGATION_HEIGHT = 65;
export const COLLAPSE_DURATION = 300;
export const OFFSET_FROM_BOTTOM_FOR_SCROLLING = 10;
export const EXTRA_WAITING_TIME_FOR_TIMEOUT = 10;
