name: web batch 1 continuous delivery

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_IP_BATCH_1 }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.INSTANCE_KEY }}
          passphrase: ${{ secrets.INSTANCE_PASSPHRASE }} 
          script: echo "${{ secrets.GIT_REPO_KEY }}" > /home/common/.ssh/id_rsa && chmod 600 /home/common/.ssh/id_rsa && cd ~ && sudo rm -rf common-web && GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:daostack/common-web.git && cd common-web && git checkout master && sudo docker build -t common-ui:latest . && docker rm -f  common-ui || true && sudo docker run -d -p 80:80 --name  common-ui common-ui:latest
