name: web batch 1 continuous delivery

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_IP_BATCH_1 }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.INSTANCE_KEY }}
          passphrase: ${{ secrets.INSTANCE_PASSPHRASE }} 
          script: echo "${{ secrets.GIT_REPO_KEY }}" > /home/common/.ssh/id_rsa
