name: Firebase CloudFunctions Test CI

on:
  push:
    paths:
      - 'packages/firebase/**'
      - 'packages/types/**'
    branches:
      - main
      - main/firebase
      - main/app
  pull_request:
    paths:
      - 'packages/firebase/**'
      - 'packages/types/**'
    branches:
      - main
      - main/firebase
      - main/app

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.20.1

      - name: Setting up Java
        uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'

      - name: Setup Lerna
        run: yarn global add lerna

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages and bootstrap project
        run: yarn install && lerna bootstrap

      - name: Setup CI environment
        run: lerna exec 'yarn ci:setup --token ${{ secrets.FIREBASE_TOKEN }}' --scope @common/firebase

      - name: Run tests
        run:  lerna exec 'yarn ci:test' --scope @common/firebase
