name: "Pull Request Labeler"
on: pull_request

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-babels: true