export enum CommonActionType {
  RESET_COMMON = "@COMMON/RESET_COMMON",

  SET_DISCUSSION_CREATION_DATA = "@COMMON/SET_DISCUSSION_CREATION_DATA",

  GET_FEED_ITEMS = "@COMMON/GET_FEED_ITEMS",
  GET_FEED_ITEMS_SUCCESS = "@COMMON/GET_FEED_ITEMS_SUCCESS",
  GET_FEED_ITEMS_FAILURE = "@COMMON/GET_FEED_ITEMS_FAILURE",
}
