export enum CommonActionType {
  RESET_COMMON = "@COMMON/RESET_COMMON",

  SET_DISCUSSION_CREATION_DATA = "@COMMON/SET_DISCUSSION_CREATION_DATA",

  CREATE_DISCUSSION = "@COMMON/CREATE_DISCUSSION",
  CREATE_DISCUSSION_SUCCESS = "@COMMON/CREATE_DISCUSSION_SUCCESS",
  CREATE_DISCUSSION_FAILURE = "@COMMON/CREATE_DISCUSSION_FAILURE",

  GET_FEED_ITEMS = "@COMMON/GET_FEED_ITEMS",
  GET_FEED_ITEMS_SUCCESS = "@COMMON/GET_FEED_ITEMS_SUCCESS",
  GET_FEED_ITEMS_FAILURE = "@COMMON/GET_FEED_ITEMS_FAILURE",

  ADD_NEW_FEED_ITEMS = "@COMMON/ADD_NEW_FEED_ITEMS",
}
